import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../core/models/enums/task_status.dart';
import '../../../../core/models/task.dart';
import '../../../../core/providers/database_provider.dart';
import '../../../../core/utils/date_utils.dart';
import '../../../../core/widgets/app_toast.dart';
import '../../../../core/widgets/confirm_dialog.dart';
import '../../../recurring/presentation/widgets/recurrence_scope_dialog.dart';
import '../../../recurring/providers/recurring_providers.dart';
import '../../domain/commands/create_task_command.dart';
import '../../domain/commands/delete_task_command.dart';
import '../../domain/conflict_resolver.dart';
import '../providers/day_tasks_provider.dart';
import '../providers/selected_date_provider.dart';
import '../providers/undo_stack_provider.dart';

/// Shared high-level scheduling actions, invoked from the context menu,
/// keyboard shortcuts and dialogs.
abstract final class TimelineActions {
  /// Duplicates [task] into the next available slot after the original.
  /// All fields are copied except id / created_at / updated_at.
  static Future<void> duplicateTask(
    BuildContext context,
    WidgetRef ref,
    Task task,
  ) async {
    if (task.startTime == null || task.endTime == null) {
      showAppToast(context, 'Only scheduled tasks can be duplicated');
      return;
    }
    final history = ref.read(undoStackProvider.notifier);
    final tasks = ref.read(dayTasksProvider).value ?? const <Task>[];
    final durationMin = task.scheduledDuration!.inMinutes;
    final originalStartMin = minutesSinceMidnight(task.startTime!);

    final slot = ConflictResolver.findNextAvailableSlot(
      durationMinutes: durationMin,
      dayTasks: tasks,
      searchFromMinutes: originalStartMin + durationMin,
    );
    if (slot == null) {
      showAppToast(context, 'No room left on this day for the copy');
      return;
    }
    final day = ref.read(selectedDateProvider);
    final start = day.add(Duration(minutes: slot));
    final end = start.add(Duration(minutes: durationMin));
    final now = DateTime.now();
    final copy = task.copyWith(
      id: '',
      startTime: start,
      endTime: end,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    );
    await history.execute(
      CreateTaskCommand(ref.read(taskRepositoryProvider), copy),
    );
    if (!context.mounted) return;
    showAppToast(context, 'Duplicated "${task.title}"');
  }

  /// Asks for confirmation, then soft-deletes via [DeleteTaskCommand].
  /// Recurring instances get an extra scope question (planner.md Chunk 4 #8):
  /// "This occurrence only" adds an exception date; "All future occurrences"
  /// ends the rule the day before this instance.
  static Future<void> deleteWithConfirmation(
    BuildContext context,
    WidgetRef ref,
    Task task,
  ) async {
    // Capture before any await so post-dialog work never touches a stale
    // provider graph.
    final viewedDate = ref.read(selectedDateProvider);
    final repository = ref.read(taskRepositoryProvider);

    final confirmed = await showConfirmDialog(
      context,
      title: 'Delete task?',
      message: '"${task.title}" will be removed from the timeline.\n'
          'You can undo this with Ctrl+Z.',
      confirmLabel: 'Delete',
    );
    if (!confirmed) return;
    if (!context.mounted) return;

    final command = DeleteTaskCommand(repository: repository, original: task);

    if (task.recurringRuleId != null) {
      final scope = await showRecurrenceScopeDialog(
        context,
        title: 'Delete recurring task',
        message:
            '"${task.title}" is generated by a recurring rule.\nWhat should be deleted?',
        thisOccurrenceLabel: 'This occurrence only',
        allFutureLabel: 'All future occurrences',
      );
      if (scope == null) return;

      await ref.read(undoStackProvider.notifier).execute(command);

      final rulesRepo = ref.read(recurringRepositoryProvider);
      if (scope == RecurrenceScope.thisOccurrence) {
        // Prevent re-materialization of exactly this date.
        if (task.startTime != null) {
          await rulesRepo.addException(
              task.recurringRuleId!, startOfDay(task.startTime!));
        }
        if (!context.mounted) return;
        showAppToast(context, 'Occurrence deleted');
      } else {
        // End the series: last allowed occurrence is the day before this one.
        if (task.startTime != null) {
          await rulesRepo.setEndDate(
            task.recurringRuleId!,
            startOfDay(task.startTime!).subtract(const Duration(days: 1)),
          );
        }
        await rulesRepo.deactivateRule(task.recurringRuleId!);
        if (!context.mounted) return;
        showAppToast(context, 'Recurring series ended');
      }
      ref.invalidate(dayMaterializationProvider(viewedDate));
      return;
    }

    await ref.read(undoStackProvider.notifier).execute(command);
  }

  /// Direct status update (not part of the reversible scheduling commands).
  static Future<void> setStatus(WidgetRef ref, Task task, TaskStatus status) {
    return ref
        .read(taskRepositoryProvider)
        .updateTask(task.copyWith(status: status));
  }
}

/// Grid fallback used when the setting has not finished loading yet; mirrors
/// [AppConstants.defaultGridMinutes].

